// lib/products-data-new.ts - Enhanced product data with all required fields

export interface Product {
  id: number;
  name: string;
  price: number;
  imageUrl: string;
  category: string;
  categoryId: string;
  description?: string;
  shortDescription?: string; // Quick highlights for product cards
  detailedDescription?: string; // In-depth product information
  unit: string; // Quantity unit (grams, liters, pieces, etc.)
  weight?: number; // Weight in grams
  discount?: number;
  inStock: boolean;
}

export const products: Product[] = [
  // Fruits Category
  {
    id: 1,
    name: "Fresh Organic Apples",
    price: 180,
    imageUrl: "/img/placeholder_image.png",
    category: "Fruits",
    categoryId: "fruits",
    description: "Sweet and juicy organic apples",
    shortDescription: "Sweet, juicy, and organically grown",
    detailedDescription: "Our organic apples are carefully selected from local farms, ensuring the highest quality and freshness. These apples are rich in fiber, vitamins, and antioxidants. Perfect for snacking, baking, or juicing.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 2,
    name: "Organic Bananas",
    price: 120,
    imageUrl: "/img/placeholder_image.png",
    category: "Fruits",
    categoryId: "fruits",
    description: "Fresh organic bananas",
    shortDescription: "Naturally sweet and nutritious",
    detailedDescription: "Premium organic bananas sourced from sustainable farms. Rich in potassium, vitamin B6, and fiber. These bananas are perfect for smoothies, baking, or as a healthy snack.",
    unit: "dozen",
    weight: 1200,
    inStock: true,
  },
  {
    id: 3,
    name: "Fresh Oranges",
    price: 150,
    imageUrl: "/img/placeholder_image.png",
    category: "Fruits",
    categoryId: "fruits",
    description: "Sweet and tangy oranges",
    shortDescription: "Vitamin C rich and refreshing",
    detailedDescription: "Fresh, juicy oranges packed with vitamin C and natural sweetness. Perfect for juicing, snacking, or adding to salads. These oranges are carefully selected for optimal ripeness and flavor.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 4,
    name: "Fresh Dates",
    price: 299,
    imageUrl: "/img/placeholder_image.png",
    category: "Fruits",
    categoryId: "fruits",
    description: "Premium quality dates",
    shortDescription: "Premium Medjool dates",
    detailedDescription: "Premium Medjool dates known for their rich, caramel-like flavor and soft texture. These dates are naturally sweet and packed with essential nutrients, fiber, and antioxidants. Perfect for snacking or as a natural sweetener.",
    unit: "500g",
    weight: 500,
    discount: 10,
    inStock: true,
  },

  // Vegetables Category
  {
    id: 5,
    name: "Fresh Broccoli",
    price: 120,
    imageUrl: "/img/placeholder_image.png",
    category: "Vegetables",
    categoryId: "vegetables",
    description: "Fresh green broccoli",
    shortDescription: "Nutrient-rich green vegetable",
    detailedDescription: "Fresh, crisp broccoli rich in vitamins C and K, fiber, and antioxidants. This versatile vegetable is perfect for steaming, stir-frying, or adding to soups and salads.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 6,
    name: "Organic Carrots",
    price: 80,
    imageUrl: "/img/placeholder_image.png",
    category: "Vegetables",
    categoryId: "vegetables",
    description: "Organic farm-fresh carrots",
    shortDescription: "Sweet and crunchy organic carrots",
    detailedDescription: "Organic carrots grown without synthetic pesticides or fertilizers. These carrots are sweet, crunchy, and rich in beta-carotene, fiber, and essential vitamins. Perfect for juicing, snacking, or cooking.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 7,
    name: "Fresh Tomatoes",
    price: 100,
    imageUrl: "/img/placeholder_image.png",
    category: "Vegetables",
    categoryId: "vegetables",
    description: "Ripe and juicy tomatoes",
    shortDescription: "Ripe, juicy, and flavorful",
    detailedDescription: "Fresh, ripe tomatoes bursting with flavor and natural sweetness. Rich in lycopene, vitamin C, and antioxidants. Perfect for salads, sandwiches, sauces, or eating fresh.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },

  // Meat Category
  {
    id: 8,
    name: "Fresh Chicken Breast",
    price: 450,
    imageUrl: "/img/placeholder_image.png",
    category: "Meat",
    categoryId: "meat",
    description: "Fresh halal chicken breast",
    shortDescription: "Fresh, halal, and lean",
    detailedDescription: "Premium quality halal chicken breast, carefully selected and prepared according to Islamic dietary guidelines. Lean, tender, and perfect for grilling, baking, or stir-frying.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 9,
    name: "Lamb Mince",
    price: 600,
    imageUrl: "/img/placeholder_image.png",
    category: "Meat",
    categoryId: "meat",
    description: "Premium quality lamb mince",
    shortDescription: "Premium quality minced lamb",
    detailedDescription: "High-quality minced lamb meat, perfect for kebabs, curries, and traditional dishes. Rich in protein and essential nutrients.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },

  // Fish Category
  {
    id: 10,
    name: "Fresh Salmon",
    price: 800,
    imageUrl: "/img/placeholder_image.png",
    category: "Fish",
    categoryId: "fish",
    description: "Fresh Atlantic salmon",
    shortDescription: "Fresh Atlantic salmon fillets",
    detailedDescription: "Premium fresh Atlantic salmon fillets, rich in omega-3 fatty acids and protein. Perfect for grilling, baking, or pan-searing.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 11,
    name: "Rohu Fish",
    price: 350,
    imageUrl: "/img/placeholder_image.png",
    category: "Fish",
    categoryId: "fish",
    description: "Fresh river rohu fish",
    shortDescription: "Fresh river rohu fish",
    detailedDescription: "Fresh river rohu fish, a popular freshwater fish known for its mild flavor and tender meat. Perfect for traditional fish curries and grilling.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },

  // Bakery Category
  {
    id: 12,
    name: "Whole Wheat Bread",
    price: 60,
    imageUrl: "/img/placeholder_image.png",
    category: "Bakery",
    categoryId: "bakery",
    description: "Fresh whole wheat bread",
    shortDescription: "Fresh whole wheat bread",
    detailedDescription: "Fresh whole wheat bread made with premium whole grain flour. Rich in fiber and nutrients, perfect for sandwiches and toast.",
    unit: "loaf",
    weight: 500,
    inStock: true,
  },
  {
    id: 13,
    name: "Croissants",
    price: 45,
    imageUrl: "/img/placeholder_image.png",
    category: "Bakery",
    categoryId: "bakery",
    description: "Buttery French croissants",
    shortDescription: "Buttery French croissants",
    detailedDescription: "Traditional French croissants made with butter and premium flour. Flaky, buttery, and perfect for breakfast or afternoon tea.",
    unit: "piece",
    weight: 60,
    inStock: true,
  },

  // Oils Category
  {
    id: 14,
    name: "Mustard Oil",
    price: 189,
    imageUrl: "/img/placeholder_image.png",
    category: "Oils",
    categoryId: "oils",
    description: "Pure mustard oil",
    shortDescription: "Pure mustard oil",
    detailedDescription: "Pure mustard oil extracted from quality mustard seeds. Rich in essential fatty acids and perfect for traditional cooking.",
    unit: "liter",
    weight: 1000,
    inStock: true,
  },
  {
    id: 15,
    name: "Olive Oil",
    price: 450,
    imageUrl: "/img/placeholder_image.png",
    category: "Oils",
    categoryId: "oils",
    description: "Extra virgin olive oil",
    shortDescription: "Extra virgin olive oil",
    detailedDescription: "Premium extra virgin olive oil, cold-pressed from quality olives. Rich in antioxidants and perfect for salads and cooking.",
    unit: "liter",
    weight: 1000,
    inStock: true,
  },
  {
    id: 16,
    name: "Coconut Oil",
    price: 280,
    imageUrl: "/img/placeholder_image.png",
    category: "Oils",
    categoryId: "oils",
    description: "Pure coconut oil",
    shortDescription: "Pure coconut oil",
    detailedDescription: "Pure coconut oil extracted from fresh coconuts. Rich in medium-chain triglycerides and perfect for cooking and skincare.",
    unit: "liter",
    weight: 1000,
    inStock: true,
  },

  // Honey Category
  {
    id: 17,
    name: "Pure Honey",
    price: 299,
    imageUrl: "/img/placeholder_image.png",
    category: "Honey",
    categoryId: "honey",
    description: "Natural pure honey",
    shortDescription: "Natural pure honey",
    detailedDescription: "Natural pure honey sourced from local beekeepers. Rich in antioxidants and natural sweetness, perfect for tea and baking.",
    unit: "500g",
    weight: 500,
    discount: 15,
    inStock: true,
  },
  {
    id: 18,
    name: "Wild Forest Honey",
    price: 399,
    imageUrl: "/img/placeholder_image.png",
    category: "Honey",
    categoryId: "honey",
    description: "Wild forest honey",
    shortDescription: "Wild forest honey",
    detailedDescription: "Wild forest honey collected from natural forest environments. Rich in unique flavors and natural health benefits.",
    unit: "500g",
    weight: 500,
    inStock: true,
  },

  // Nuts Category
  {
    id: 19,
    name: "Almonds",
    price: 800,
    imageUrl: "/img/placeholder_image.png",
    category: "Nuts",
    categoryId: "nuts",
    description: "Premium quality almonds",
    shortDescription: "Premium quality almonds",
    detailedDescription: "Premium quality almonds rich in protein, healthy fats, and vitamin E. Perfect for snacking, baking, or adding to salads.",
    unit: "500g",
    weight: 500,
    inStock: true,
  },
  {
    id: 20,
    name: "Cashews",
    price: 750,
    imageUrl: "/img/placeholder_image.png",
    category: "Nuts",
    categoryId: "nuts",
    description: "Premium cashews",
    shortDescription: "Premium cashews",
    detailedDescription: "Premium quality cashews, rich in healthy fats and minerals. Perfect for snacking, cooking, or adding to desserts.",
    unit: "500g",
    weight: 500,
    inStock: true,
  },

  // Seeds Category
  {
    id: 21,
    name: "Chia Seeds",
    price: 350,
    imageUrl: "/img/placeholder_image.png",
    category: "Seeds",
    categoryId: "seeds",
    description: "Organic chia seeds",
    shortDescription: "Organic chia seeds",
    detailedDescription: "Organic chia seeds rich in omega-3 fatty acids, fiber, and protein. Perfect for smoothies, puddings, or sprinkling on food.",
    unit: "250g",
    weight: 250,
    inStock: true,
  },
  {
    id: 22,
    name: "Sunflower Seeds",
    price: 200,
    imageUrl: "/img/placeholder_image.png",
    category: "Seeds",
    categoryId: "seeds",
    description: "Roasted sunflower seeds",
    shortDescription: "Roasted sunflower seeds",
    detailedDescription: "Roasted sunflower seeds rich in vitamin E and healthy fats. Perfect for snacking, salads, or baking.",
    unit: "250g",
    weight: 250,
    inStock: true,
  },

  // Grocery Category
  {
    id: 23,
    name: "Basmati Rice",
    price: 120,
    imageUrl: "/img/placeholder_image.png",
    category: "Grocery",
    categoryId: "grocery",
    description: "Premium basmati rice",
    shortDescription: "Premium basmati rice",
    detailedDescription: "Premium quality basmati rice with long, aromatic grains. Perfect for biryanis, pulaos, and other rice dishes.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },
  {
    id: 24,
    name: "Red Lentils",
    price: 80,
    imageUrl: "/img/placeholder_image.png",
    category: "Grocery",
    categoryId: "grocery",
    description: "Organic red lentils",
    shortDescription: "Organic red lentils",
    detailedDescription: "Organic red lentils rich in protein and fiber. Perfect for soups, curries, and traditional lentil dishes.",
    unit: "kg",
    weight: 1000,
    inStock: true,
  },

  // Dairy Category
  {
    id: 25,
    name: "Fresh Milk",
    price: 90,
    imageUrl: "/img/placeholder_image.png",
    category: "Dairy",
    categoryId: "dairy",
    description: "Fresh organic milk",
    shortDescription: "Fresh organic milk",
    detailedDescription: "Fresh organic milk from grass-fed cows. Rich in calcium, protein, and essential vitamins. Perfect for drinking, cooking, or making dairy products.",
    unit: "liter",
    weight: 1000,
    inStock: true,
  },
  {
    id: 26,
    name: "Greek Yogurt",
    price: 150,
    imageUrl: "/img/placeholder_image.png",
    category: "Dairy",
    categoryId: "dairy",
    description: "Creamy Greek yogurt",
    shortDescription: "Creamy Greek yogurt",
    detailedDescription: "Creamy Greek yogurt rich in protein and probiotics. Perfect for breakfast, smoothies, or as a healthy snack.",
    unit: "500g",
    weight: 500,
    inStock: true,
  },

  // Spices Category
  {
    id: 27,
    name: "Turmeric Powder",
    price: 120,
    imageUrl: "/img/placeholder_image.png",
    category: "Spices",
    categoryId: "spices",
    description: "Pure turmeric powder",
    shortDescription: "Pure turmeric powder",
    detailedDescription: "Pure turmeric powder known for its anti-inflammatory properties and vibrant color. Perfect for curries, rice dishes, and health drinks.",
    unit: "100g",
    weight: 100,
    inStock: true,
  },
  {
    id: 28,
    name: "Cinnamon Powder",
    price: 100,
    imageUrl: "/img/placeholder_image.png",
    category: "Spices",
    categoryId: "spices",
    description: "Ground cinnamon powder",
    shortDescription: "Ground cinnamon powder",
    detailedDescription: "Ground cinnamon powder with warm, sweet flavor. Perfect for baking, desserts, and spiced beverages.",
    unit: "100g",
    weight: 100,
    inStock: true,
  },

  // Snacks Category
  {
    id: 29,
    name: "Mixed Nuts",
    price: 450,
    imageUrl: "/img/placeholder_image.png",
    category: "Snacks",
    categoryId: "snacks",
    description: "Premium mixed nuts",
    shortDescription: "Premium mixed nuts",
    detailedDescription: "Premium mixed nuts including almonds, cashews, walnuts, and pistachios. Perfect for snacking or adding to trail mixes.",
    unit: "500g",
    weight: 500,
    inStock: true,
  },
  {
    id: 30,
    name: "Dark Chocolate",
    price: 200,
    imageUrl: "/img/placeholder_image.png",
    category: "Snacks",
    categoryId: "snacks",
    description: "70% dark chocolate",
    shortDescription: "70% dark chocolate",
    detailedDescription: "Premium 70% dark chocolate rich in antioxidants and natural cocoa flavor. Perfect for snacking or baking.",
    unit: "100g",
    weight: 100,
    inStock: true,
  },

  // Household Category
  {
    id: 31,
    name: "Organic Soap",
    price: 80,
    imageUrl: "/img/placeholder_image.png",
    category: "Household",
    categoryId: "household",
    description: "Natural organic soap",
    shortDescription: "Natural organic soap",
    detailedDescription: "Natural organic soap made with pure ingredients and essential oils. Gentle on skin and environmentally friendly.",
    unit: "piece",
    weight: 100,
    inStock: true,
  },
  {
    id: 32,
    name: "Bamboo Toothbrush",
    price: 60,
    imageUrl: "/img/placeholder_image.png",
    category: "Household",
    categoryId: "household",
    description: "Eco-friendly bamboo toothbrush",
    shortDescription: "Eco-friendly bamboo toothbrush",
    detailedDescription: "Eco-friendly bamboo toothbrush with soft bristles. Biodegradable and perfect for sustainable oral care.",
    unit: "piece",
    weight: 30,
    inStock: true,
  },
];

// Helper functions for product data
export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((product) => product.categoryId === categoryId);
}

export function getCategoriesWithCounts() {
  const categories = [
    { id: "fruits", name: "Fruits", icon: "Apple" },
    { id: "vegetables", name: "Vegetables", icon: "Carrot" },
    { id: "meat", name: "Meat", icon: "Drumstick" },
    { id: "fish", name: "Fish", icon: "Fish" },
    { id: "bakery", name: "Bakery", icon: "Croissant" },
    { id: "dairy", name: "Dairy & Eggs", icon: "Cheese" },
    { id: "spices", name: "Spices & Condiments", icon: "Flame" },
    { id: "grains", name: "Rice, Lentils & Staples", icon: "Wheat" },
    { id: "oils", name: "Cooking Oils & Ghee", icon: "Oil" },
    { id: "snacks", name: "Snacks & Beverages", icon: "Cookie" },
    { id: "household", name: "Household Essentials", icon: "Home" },
  ];

  return categories.map((category) => ({
    ...category,
    productCount: products.filter((p) => p.categoryId === category.id).length,
  }));
}
